name: config

env:
    VAR1: xxxxxxxxxxxxxx
    VAR2: yyyyyyyyyyyyyy
    VAR3: zzzzzzzzzzzzzz
    VAR_APP: '@_xxxx import xxxxx'

on:
  workflow_call:

jobs:
    setup-variables:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3

        - id: is-dev
          name: 'DEV: set vars'
          run: |
           echo "NEW_VAR1r=${{ env.VAR1 }}" >> $GITHUB_ENV
           echo "{{ NEW_VAR1 }}"



