name: deploy

on:
  workflow_call:
    inputs:
      VAR1:
        required: true
        type: string

jobs:
  set-vars:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - id: display
        name: display-vars
        run: |
          echo "${{ VAR1 }}"
        with:
          VAR1: ${{ input.VAR1 }}
