name: deploy

on:
  workflow_call:
    inputs:
      VAR1:
        required: true
        type: string

jobs:
  set-vars:
    runs-on: macos-latest
    steps:
      - name: display-vars
        run: |
          echo "${{ input.VAR1 }}"
        with:
          VAR1: ${{ input.VAR1 }}
          