name: iOS CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      main

jobs:
  init:
    runs-on: macos-latest
    steps:
      #- name: checkout code
      #  uses: actions/checkoutcode@v2

      - name: setup Xcode
        run: xcodebuild -version

      - name: check archyteture
        run: uname -a
  
  build-ios:
    - name: build ios
      needs: [init]
      uses: ricardoysh/pipeline-core/.github/workflows/build-ios.yml@main
          
        
