name: iOS CI Pipeline

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     main

jobs:
  init:
    runs-on: macos-latest
    steps:
      #- name: checkout code
      #  uses: actions/checkoutcode@v2

      # - name: setup Xcode
      #   run: xcodebuild -version

      - name: Set environment variable
        id: set_var
        run: |
          MY_VAR="Hello, World!"
          echo "MY_VAR=$MY_VAR" >> $GITHUB_ENV
          echo "::set-output name=my_var::$MY_VAR"

      - name: Output the variable
        run: echo "The variable is $MY_VAR"

      # - name: display variables
      #   run: echo "$RUNNER_OS"
       
  ## build da aplicacao ##
  # build:
  #   name: build-ios
  #   needs: [init]
  #   uses: ricardoysh/pipeline-core/.github/workflows/build-ios.yml@main
  # ## escaneamento de cod com sonar ##        
  # sonar:
  #   name: run sonar scan
  #   needs: [build]
  #   uses: ricardoysh/pipeline-core/.github/workflows/sonar-ios.yml@main
  # ## ofuscacao de codigo ##
  # obfuscate:
  #   name: run obfuscate code
  #   needs: [sonar]
  #   uses: ricardoysh/pipeline-core/.github/workflows/obfuscate-ios.yml@main

  # approve:
  #   runs-on: ubuntu-latest
  #   needs: [obfuscate]
  #   steps:
  #     - name: Wait for approval
  #       uses: hmarr/approve-action@v2
  # teste
  
  # releae-app:
  #   name: release ios app
  #   needs: [obfuscate]
  #   uses: ricardoysh/pipeline-core/.github/workflows/release-ios.yml@main
