name: pipeline-ios-test

on:
  # workflow_dispatch:
  push:
    branches:
      - main
    # pull_request:
  #   branches:
  #     main

jobs:
  init:
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install yq
        run: jq --version

      - name: Load variables
        run: |
          for vars in $(yq e '.variables[] | .name + "=" + (.value | @sh)' variables/variables.yml); do
            echo "$vars"
            echo "$vars" >> $GITHUB_ENV
          done
      - name: debug msg
        run: |
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"

      - name: Set environment variable
        run: echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV
  
      - name: Use environment variable
        run: |
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
          echo "VAR1 ---> $MY_VAR_01"
          echo "VAR2 ---> $MY_VAR_02"
          echo "VAR3 ---> $MY_VAR_03"
          echo "VAR4 ---> $MY_VAR_04"
        

      # - name: display variables
      #   run: echo "$RUNNER_OS"
       
  ## build da aplicacao ##
  # build:
  #   name: build-ios
  #   needs: [init]
  #   uses: ricardoysh/pipeline-core/.github/workflows/build-ios.yml@main
  # ## escaneamento de cod com sonar ##        
  # sonar:
  #   name: run sonar scan
  #   needs: [build]
  #   uses: ricardoysh/pipeline-core/.github/workflows/sonar-ios.yml@main
  # ## ofuscacao de codigo ##
  # obfuscate:
  #   name: run obfuscate code
  #   needs: [sonar]
  #   uses: ricardoysh/pipeline-core/.github/workflows/obfuscate-ios.yml@main

  # approve:
  #   runs-on: ubuntu-latest
  #   needs: [obfuscate]
  #   steps:
  #     - name: Wait for approval
  #       uses: hmarr/approve-action@v2
  # teste
  
  # releae-app:
  #   name: release ios app
  #   needs: [obfuscate]
  #   uses: ricardoysh/pipeline-core/.github/workflows/release-ios.yml@main
