name: set-variables

# definir variáveis e seu valor aqui
env:
    VAR1: xxxxxxxxxxxxxx
    VAR2: yyyyyyyyyyyyyy
    VAR3: zzzzzzzzzzzzzz
    VAR_APP: '@_xxxx import xxxxx'

on:
  workflow_call:
    outputs:
      NEW_VAR1:
        value: ${{ jobs.setup-variables.outputs.NEW_VAR1 }}

jobs:
    setup-variables:
      runs-on: macos-latest
      outputs:
       NEW_VAR1: ${{ steps.resolved.outputs.VAR1 }}
       
      steps:
        - uses: actions/checkout@v3

        - id: is-dev
          name: 'DEV: set vars'
          run: |
           echo "NEW_VAR1=${{ env.VAR1 }}" >> $GITHUB_ENV


        - id: resolved
          name: set outputs
          run: |
             echo "NEW_VAR1=${{ env.NEW_VAR1 }}" >> $GITHUB_OUTPUT


