name: Test Assume Role

on:
  push

jobs:
  init:
    runs-on: self-hosted

    steps:
      - name: Install AWS CLI
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install unzip -y
          sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip awscliv2.zip
          sudo ./aws/install
          aws --version

          aws sts get-caller-identity

