name: Test Assume Role

on:
  workflow_dispatch

jobs:
  init:
    runs-on: self-hosted

    steps:
      - name: Install AWS CLI
        run: |
          # Install dependencies
          apt-get update
          apt-get install unzip -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

          aws sts get-caller-identity

